// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetakesAllocatorCore.Db;

#nullable disable

namespace RetakesAllocator.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20240116025022_BigIntTime")]
    partial class BigIntTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("RetakesAllocatorCore.Db.UserSetting", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WeaponPreferences")
                        .HasMaxLength(10000)
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
